### ISSUE TITLE
Dependency on Test::Exception undeclared

### ISSUE THREAD

**Issue by andk** [pplu/io-k8s-p5#3]
As per subject. Grep:

http://search.cpan.org/grep?release=IO-K8s-0.02;string=Test::Exception;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/94952045

**Comment by pplu** [comment]
Hi,

   Thank you for your report. It's fixed on master (PR by @manwar), and will be pushed briefly to CPAN
