### ISSUE TITLE
Invitation for collaborating the WIP offical perl client

### ISSUE THREAD

**Issue by yue9944882** [pplu/io-k8s-p5#4]
Hi @pplu,

I'm Min, one of maintainer stuff from kubernetes community. We're starting a repo [kubernetes-client/perl](https://github.com/kubernetes-client/perl) to converge an offical client SDK for the community based on OpenAPI generator which aligns w/ the other offical polyglot clients. And I see that you're active maintaining perl client SDK for cloud projects for years. Are you interested in collaborating the repo? Mail me or DM me at slack [slack.k8s.io](http://slack.k8s.io/) for detail. 

Thanks,
Min

**Comment by pplu** [comment]
Hi!

  Thanks for the invitation! I'll try to join slack and chat with you. Also take a look at https://github.com/pplu/kubernetes-rest. It's being generated from the Kubernetes swagger definitions already. Should be fairly equivalent to the client you're generating from swagger definitions.

**Comment by yue9944882** [comment]
great. 

> Should be fairly equivalent to the client you're generating from swagger definitions.

true. actually we're migrating from [swagger-generator](https://github.com/swagger-api/swagger-codegen) to [openapi-generator](https://github.com/OpenAPITools/openapi-generator) to make all the kubernetes clients standing on a same basis. there're slightly different tho. 

ptal [https://github.com/kubernetes-client/gen/pull/113](https://github.com/kubernetes-client/gen/pull/113) that how we manage all the generation scripts in a single repo
